"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Margin = exports.Path = exports.Polygon = exports.Grid = exports.Rect = exports.Position = exports.Size = void 0;
const Size_1 = __importDefault(require("./Dimension/Size"));
exports.Size = Size_1.default;
const Position_1 = __importDefault(require("./Dimension/Position"));
exports.Position = Position_1.default;
const Rect_1 = __importDefault(require("./Dimension/Rect"));
exports.Rect = Rect_1.default;
const Grid_1 = __importDefault(require("./Dimension/Grid"));
exports.Grid = Grid_1.default;
const Polygon_1 = __importDefault(require("./Dimension/Polygon"));
exports.Polygon = Polygon_1.default;
const Path_1 = __importDefault(require("./Dimension/Path"));
exports.Path = Path_1.default;
const Margin_1 = __importDefault(require("./Dimension/Margin"));
exports.Margin = Margin_1.default;
